# Get what we need to build (GCC + CMake)
FROM dockcross/base

RUN apt-get update && apt-get install -y \
    dos2unix

COPY build.sh /bin/build.sh
COPY runtests.sh /bin/runtests.sh

RUN dos2unix /bin/build.sh &&\
    dos2unix /bin/runtests.sh