# Get what we need to build (GCC + CMake)
FROM dockcross/base

# Setup working directory
WORKDIR /tmp/app
# Copy source + cmake-files into workdir in container
COPY . ./
WORKDIR ./build

# Generate & build source using cmake
RUN cmake .. &&\
    cmake --build . --config Release &&\
    ctest -C Release