environments:
  linux:
    pipelines:
      - build-artifact
      - acceptance-tests
      - analyze
pipelines:
  build-artifact:
    group: hello-cd
    materials:
      git-repo:  # material name
        git: /source
        branch: cross-compile-gcc
    stages:
      - build: # stage name
          clean_workspace: true
          jobs:
            build: # job name
              artifacts:
                - build:
                    source: build
                    destination: ./
              tasks:
                - exec: # type of task
                    command: ./docker/run-script.sh
                    arguments:
                     - > 
                          ./scripts/install-dependencies.sh &&
                          ./scripts/build.sh &&
                          ./scripts/install.sh
      - run-unit-tests:
          clean_workspace: true
          jobs:
            run-unit-tests:
              artifacts:
                - test:
                    source: build/output/reports/*tests.xml
                    destination: "tests"
              tasks:
                - fetch:
                   pipeline: build-artifact
                   stage: build
                   job: build
                   source: build
                   destination: ./
                - exec:
                    command: ./docker/run-script.sh
                    arguments:
                     - >
                          ./scripts/run-unit-tests.sh &&
                          ./scripts/install.sh
  acceptance-tests:
    group: hello-cd
    materials:
      git-repo:
        git: /source
        branch: cross-compile-gcc
      upstream:
        pipeline: build-artifact
        stage: run-unit-tests
    stages:
      - run-tests:
          jobs:
            run-tests:
              artifacts:
                - build:
                    source: build/output/reports/
                    destination: "reports"
              tasks:
                - fetch:
                    pipeline: build-artifact
                    stage: build
                    job: build
                    source: build
                    destination: ./
                - exec:
                    command: ./docker/run-script.sh
                    arguments:
                      - >
                          ./scripts/run-acceptance-tests.sh &&
                          ./scripts/install.sh
  analyze:
    group: hello-cd
    materials:
      git-repo:
        git: /source
        branch: cross-compile-gcc
      upstream:
        pipeline: build-artifact
        stage: run-unit-tests
    stages:
      - code-coverage:
          jobs:
            code-coverage:
              artifacts:
                - build:
                    source: build/output/reports/
                    destination: "reports"
              tabs:
                mylib-cov: reports/mylib_coverage_analysis/index.html
                myutils-cov: reports/myutils_coverage_analysis/index.html
              tasks:
                - exec:
                    command: ./docker/run-script.sh
                    arguments:
                      - >
                          ./scripts/install-dependencies.sh Debug &&
                          ./scripts/build.sh Debug &&
                          ./scripts/run-coverage-analysis.sh Debug &&
                          ./scripts/install.sh Debug
      - static-analysis:
          jobs:
            static-analysis:
              artifacts:
                - build:
                    source: build/output/reports/
                    destination: "reports"
                - test:
                    source: build/output/reports/*junit*.xml
                    destination: "tests"
              tabs:
                mylib-analys: reports/mylib_static_analysis_html/index.html
                myutils-analys: reports/myutils_static_analysis_html/index.html
              tasks:
                - fetch:
                    pipeline: build-artifact
                    stage: build
                    job: build
                    source: build
                    destination: ./
                - exec:
                    command: ./docker/run-script.sh
                    arguments:
                      - >
                          ./scripts/run-static-analysis.sh &&
                          ./scripts/install.sh