environments:
  docker:
    pipelines:
      - build-on-docker-agent
pipelines:
  build-on-docker-agent:
    group: hello-cd
    materials:
      git-repo:  # material name
        git: /source
        branch: master
    stages:
      - build: # stage name
          clean_workspace: true
          jobs:
            build-artifact: # job name
              artifacts:
                - test:
                   source: build/output/reports/*tests.xml
                   destination: "tests"
              tasks:
                - exec: # type of task
                    command: ./docker/run-script.sh
                    arguments:
                     - "./scripts/build.sh"
      - analyze: # stage name
          clean_workspace: true
          jobs:
            code-analysis:
              artifacts:
                - build:
                   source: build/output/reports/
                   destination: "reports"
                - test:
                   source: build/output/reports/*junit*.xml
                   destination: "tests"
              tabs:
                mylib-cov: reports/mylib_coverage_analysis/index.html
                myutils-cov: reports/myutils_coverage_analysis/index.html
                mylib-analys: reports/mylib_static_analysis_html/index.html
                myutils-analys: reports/myutils_static_analysis_html/index.html
              tasks:
                - exec:
                    command: ./docker/run-script.sh
                    arguments:
                     - "./scripts/run-coverage-analysis.sh && ./scripts/run-static-analysis.sh"