environments:
  docker:
    pipelines:
      - build-on-docker-agent
pipelines:
  build-on-docker-agent:
    group: hello-cd
    materials:
      git-remote:  # material name
        git: /source
        branch: master
    stages:
      - build: # stage name
          clean_workspace: true
          jobs:
            build-artifact: # job name
              tasks:
                - exec: # type of task
                    command: ./docker/build.sh